### PR TITLE
Initial layout for review

### PR DESCRIPTION
**Pull request by djworth**
The goal of this PR is to kick off the conversation of how this
library should be structured.

Looking for feedback :)

### CODE REVIEW

**Comment by antongulenko** [comment]
IMO, this repository could contains both the library for interacting with `cardano-wallet`, and also a basic CLI that wraps the API in a simple way. More or less, an example on how to use the library, and possibly also useful in a more general sense. For Go projects that contain both library code and binaries, I like the structure to have top-level `cmd/` and a `pkg/` folders, alongside the `go.mod` file - but we can also keep it simpler. Sorry, I could not yet take a look at the actual types you defined, just dumped some quick thoughts.

**Comment by djworth** [comment]
> IMO, this repository could contains both the library for interacting with `cardano-wallet`, and also a basic CLI that wraps the API in a simple way. More or less, an example on how to use the library, and possibly also useful in a more general sense. For Go projects that contain both library code and binaries, I like the structure to have top-level `cmd/` and a `pkg/` folders, alongside the `go.mod` file - but we can also keep it simpler. Sorry, I could not yet take a look at the actual types you defined, just dumped some quick thoughts.

I like the idea of having a basic CLI that wraps the API.

**Comment by antongulenko** [comment]
Hey there, I have started generating client-side Go code from the Swagger specification of `cardano-wallet` in [my fork](https://github.com/antongulenko/cardano-wallet-client/), using [oapi-codegen](https://github.com/deepmap/oapi-codegen). The generated code seems to have problems with OpenAPI enums, which I will investigate. Folders and files in my fork are just for playing around, for a PR I will move/rename in a way that we agree on.

Once the generated code works, I would probably add some helpers for connecting to a node, and maybe a small test-cli for some GET commands. Do you know the best way to play with this? Does my local instance of Daedalus support the `cardano-wallet` API, or is there some "mock-wallet" that should be used?

**Review by Sultan05500 — COMMENTED** [review]
Fin

**Pull request closed without merging**
